CREATE TABLE `currency_events` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `Stream` VARCHAR(200) DEFAULT NULL,
  `EventType` VARCHAR(50) DEFAULT NULL,
  `EventTimestamp` bigint NOT NULL,
  `Symbol` VARCHAR(50) NOT NULL,
  `KlineStartTime` bigint NOT NULL,
  `KlineCloseTime` bigint NOT NULL,
  `Interval` VARCHAR(10) NOT NULL,
  `FirstTradeId` bigint DEFAULT NULL,
  `LastTradeId` bigint DEFAULT NULL,
  `OpenPrice`  REAL(16,5) NOT NULL,
  `ClosePrice`  REAL(16,5) NOT NULL,
  `HighPrice`  REAL(16,5) NOT NULL,
  `LowPrice`  REAL(16,5) NOT NULL,
  `BaseAssetVolume` VARCHAR(50) DEFAULT NULL,
  `NumberOfTrades` bigint DEFAULT NULL,
  `IsKlineClosed` TINYINT DEFAULT NULL,
  `QuoteAssetVolume` VARCHAR(50) DEFAULT NULL,
  `TakerBuyBaseAssetVolume` VARCHAR(50) DEFAULT NULL,
  `TakerBuyQuoteAssetVolume` VARCHAR(50) DEFAULT NULL,
  `TransactionId` VARCHAR(50) NOT NULL,
  `InsertTimestamp` datetime NOT NULL,
  PRIMARY KEY (`TransactionId`),
  KEY `id_index` (`ID`),
  KEY `EventTimestamp_index` (`EventTimestamp`)
) ENGINE=InnoDB AUTO_INCREMENT=21539 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci